{
  "name": "TourismAnalytics",
  "compatibilityLevel": 1567,
  "model": {
    "culture": "en-IN",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "discourageImplicitMeasures": false,
    "sourceQueryCulture": "en-IN",
    "expressions": [
      {
        "name": "ServerName",
        "kind": "m",
        "expression": [
          "\"localhost\\SQLEXPRESS\"",
          "meta [IsParameterQuery=true, List={\"localhost\\SQLEXPRESS\", \"localhost\", \".\\SQLEXPRESS\", \"(localdb)\\MSSQLLocalDB\"}, DefaultValue=\"localhost\\SQLEXPRESS\", Type=\"Text\", IsParameterQueryRequired=true]"
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ]
      },
      {
        "name": "DatabaseName",
        "kind": "m",
        "expression": [
          "\"TourismDW\"",
          "meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]"
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ]
      }
    ],
    "tables": [
      {
        "name": "DimDate",
        "columns": [
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "0",
            "isHidden": true
          },
          {
            "name": "FullDate",
            "dataType": "dateTime",
            "sourceColumn": "FullDate",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "dd mmm yyyy",
            "isKey": true
          },
          {
            "name": "Year",
            "dataType": "int64",
            "sourceColumn": "Year",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "0"
          },
          {
            "name": "Quarter",
            "dataType": "string",
            "sourceColumn": "Quarter",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "MonthNo",
            "dataType": "int64",
            "sourceColumn": "MonthNo",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "0",
            "isHidden": true
          },
          {
            "name": "MonthName",
            "dataType": "string",
            "sourceColumn": "MonthName",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "sortByColumn": "MonthNo"
          },
          {
            "name": "MonthYear",
            "dataType": "string",
            "sourceColumn": "MonthYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "sortByColumn": "DateKey"
          },
          {
            "name": "DayOfMonth",
            "dataType": "int64",
            "sourceColumn": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "0"
          },
          {
            "name": "DayName",
            "dataType": "string",
            "sourceColumn": "DayName",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "WeekOfYear",
            "dataType": "int64",
            "sourceColumn": "WeekOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "0"
          },
          {
            "name": "DayOfYear",
            "dataType": "int64",
            "sourceColumn": "DayOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "0",
            "isHidden": true
          },
          {
            "name": "IsWeekend",
            "dataType": "boolean",
            "sourceColumn": "IsWeekend",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "isHidden": true
          },
          {
            "name": "Season",
            "dataType": "string",
            "sourceColumn": "Season",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "FinancialYear",
            "dataType": "string",
            "sourceColumn": "FinancialYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "IsPeakSeason",
            "dataType": "boolean",
            "sourceColumn": "IsPeakSeason",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Season Sort",
            "dataType": "int64",
            "expression": "SWITCH( DimDate[Season], \"Winter\", 1, \"Summer\", 2, \"Monsoon\", 3, \"Autumn\", 4, 5 )",
            "isDataTypeInferred": true,
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "0"
          },
          {
            "type": "calculated",
            "name": "Peak Season Label",
            "dataType": "string",
            "expression": "IF ( DimDate[IsPeakSeason], \"Peak Season\", \"Off Peak\" )",
            "isDataTypeInferred": true,
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Year Quarter",
            "dataType": "string",
            "expression": "DimDate[Year] & \"-\" & DimDate[Quarter]",
            "isDataTypeInferred": true,
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DimDate",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(ServerName, DatabaseName),",
                "    dbo_DimDate = Source{[Schema=\"dbo\",Item=\"DimDate\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(dbo_DimDate,{{\"FullDate\", type date}}),",
                "    #\"Sorted Rows\" = Table.Sort(#\"Changed Type\",{{\"DateKey\", Order.Ascending}})",
                "in",
                "    #\"Sorted Rows\""
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Calendar Hierarchy",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Quarter"
              },
              {
                "name": "MonthName",
                "ordinal": 2,
                "column": "MonthName"
              }
            ]
          }
        ],
        "dataCategory": "Time",
        "description": "Conformed calendar dimension. Marked as the model date table for time intelligence.",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_MarkedDateTable",
            "value": "true"
          }
        ]
      },
      {
        "name": "DimDestination",
        "columns": [
          {
            "name": "DestinationID",
            "dataType": "int64",
            "sourceColumn": "DestinationID",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "0",
            "isHidden": true
          },
          {
            "name": "DestinationName",
            "dataType": "string",
            "sourceColumn": "DestinationName",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "Place"
          },
          {
            "name": "City",
            "dataType": "string",
            "sourceColumn": "City",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "City"
          },
          {
            "name": "StateProvince",
            "dataType": "string",
            "sourceColumn": "StateProvince",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "StateOrProvince"
          },
          {
            "name": "Country",
            "dataType": "string",
            "sourceColumn": "Country",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "Country"
          },
          {
            "name": "Region",
            "dataType": "string",
            "sourceColumn": "Region",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Continent",
            "dataType": "string",
            "sourceColumn": "Continent",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "Continent"
          },
          {
            "name": "DestinationType",
            "dataType": "string",
            "sourceColumn": "DestinationType",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Latitude",
            "dataType": "double",
            "sourceColumn": "Latitude",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "#,0.00",
            "dataCategory": "Latitude"
          },
          {
            "name": "Longitude",
            "dataType": "double",
            "sourceColumn": "Longitude",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "#,0.00",
            "dataCategory": "Longitude"
          },
          {
            "name": "CostIndex",
            "dataType": "double",
            "sourceColumn": "CostIndex",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "#,0.00"
          },
          {
            "name": "PopularityIndex",
            "dataType": "double",
            "sourceColumn": "PopularityIndex",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "#,0.00"
          },
          {
            "name": "IsDomestic",
            "dataType": "boolean",
            "sourceColumn": "IsDomestic",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "isHidden": true
          },
          {
            "type": "calculated",
            "name": "Travel Scope",
            "dataType": "string",
            "expression": "IF ( DimDestination[IsDomestic], \"Domestic\", \"International\" )",
            "isDataTypeInferred": true,
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Destination Label",
            "dataType": "string",
            "expression": "DimDestination[DestinationName] & \" (\" & DimDestination[Country] & \")\"",
            "isDataTypeInferred": true,
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Cost Tier",
            "dataType": "string",
            "expression": "SWITCH ( TRUE(),\n    DimDestination[CostIndex] >= 1.8, \"1. Premium\",\n    DimDestination[CostIndex] >= 1.2, \"2. Upper Mid\",\n    DimDestination[CostIndex] >= 0.8, \"3. Mid\",\n    \"4. Value\" )",
            "isDataTypeInferred": true,
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DimDestination",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(ServerName, DatabaseName),",
                "    dbo_DimDestination = Source{[Schema=\"dbo\",Item=\"DimDestination\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(dbo_DimDestination,{{\"Latitude\", type number}, {\"Longitude\", type number}}),",
                "    #\"Trimmed Text\" = Table.TransformColumns(#\"Changed Type\",{{\"DestinationName\", Text.Trim, type text}, {\"Country\", Text.Trim, type text}})",
                "in",
                "    #\"Trimmed Text\""
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Geography Hierarchy",
            "levels": [
              {
                "name": "Continent",
                "ordinal": 0,
                "column": "Continent"
              },
              {
                "name": "Country",
                "ordinal": 1,
                "column": "Country"
              },
              {
                "name": "DestinationName",
                "ordinal": 2,
                "column": "DestinationName"
              }
            ]
          }
        ],
        "description": "Destination master with geography for map visuals and a drill-down hierarchy.",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "DimTraveller",
        "columns": [
          {
            "name": "TravellerID",
            "dataType": "int64",
            "sourceColumn": "TravellerID",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "0",
            "isHidden": true
          },
          {
            "name": "TravellerName",
            "dataType": "string",
            "sourceColumn": "TravellerName",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Gender",
            "dataType": "string",
            "sourceColumn": "Gender",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Age",
            "dataType": "int64",
            "sourceColumn": "Age",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "0"
          },
          {
            "name": "AgeBand",
            "dataType": "string",
            "sourceColumn": "AgeBand",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Nationality",
            "dataType": "string",
            "sourceColumn": "Nationality",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "Country"
          },
          {
            "name": "SignupDate",
            "dataType": "dateTime",
            "sourceColumn": "SignupDate",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "dd mmm yyyy"
          },
          {
            "name": "CustomerSegment",
            "dataType": "string",
            "sourceColumn": "CustomerSegment",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "LoyaltyTier",
            "dataType": "string",
            "sourceColumn": "LoyaltyTier",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "sortByColumn": "LoyaltyTierSort"
          },
          {
            "name": "IsRepeatCustomer",
            "dataType": "boolean",
            "sourceColumn": "IsRepeatCustomer",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Tenure Days",
            "dataType": "int64",
            "expression": "DATEDIFF ( DimTraveller[SignupDate], DATE ( 2026, 12, 31 ), DAY )",
            "isDataTypeInferred": true,
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "0"
          },
          {
            "type": "calculated",
            "name": "Tenure Band",
            "dataType": "string",
            "expression": "SWITCH ( TRUE(),\n    DimTraveller[Tenure Days] >= 900, \"1. Long Standing (2y+)\",\n    DimTraveller[Tenure Days] >= 540, \"2. Established (1.5-2y)\",\n    DimTraveller[Tenure Days] >= 180, \"3. Growing (6m-1.5y)\",\n    \"4. New (<6m)\" )",
            "isDataTypeInferred": true,
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "LoyaltyTierSort",
            "dataType": "int64",
            "sourceColumn": "LoyaltyTierSort",
            "formatString": "0",
            "summarizeBy": "none",
            "isHidden": true,
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DimTraveller",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(ServerName, DatabaseName),",
                "    dbo_DimTraveller = Source{[Schema=\"dbo\",Item=\"DimTraveller\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(dbo_DimTraveller,{{\"SignupDate\", type date}}),",
                "    #\"Cleaned Names\" = Table.TransformColumns(#\"Changed Type\",{{\"TravellerName\", each Text.Proper(Text.Trim(_)), type text}}),",
                "    #\"Added Tier Sort\" = Table.AddColumn(#\"Cleaned Names\", \"LoyaltyTierSort\", each if [LoyaltyTier] = \"Blue\" then 1 else if [LoyaltyTier] = \"Silver\" then 2 else if [LoyaltyTier] = \"Gold\" then 3 else if [LoyaltyTier] = \"Platinum\" then 4 else 5, Int64.Type)",
                "in",
                "    #\"Added Tier Sort\""
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Customer Hierarchy",
            "levels": [
              {
                "name": "CustomerSegment",
                "ordinal": 0,
                "column": "CustomerSegment"
              },
              {
                "name": "LoyaltyTier",
                "ordinal": 1,
                "column": "LoyaltyTier"
              },
              {
                "name": "TravellerName",
                "ordinal": 2,
                "column": "TravellerName"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "DimAccommodation",
        "columns": [
          {
            "name": "AccommodationID",
            "dataType": "int64",
            "sourceColumn": "AccommodationID",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "0",
            "isHidden": true
          },
          {
            "name": "AccommodationName",
            "dataType": "string",
            "sourceColumn": "AccommodationName",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "AccommodationType",
            "dataType": "string",
            "sourceColumn": "AccommodationType",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "StarRating",
            "dataType": "int64",
            "sourceColumn": "StarRating",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "0"
          },
          {
            "name": "DestinationID",
            "dataType": "int64",
            "sourceColumn": "DestinationID",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "0",
            "isHidden": true
          },
          {
            "name": "PriceIndex",
            "dataType": "double",
            "sourceColumn": "PriceIndex",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "#,0.00"
          },
          {
            "name": "AvgRating",
            "dataType": "double",
            "sourceColumn": "AvgRating",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "#,0.00"
          },
          {
            "type": "calculated",
            "name": "Star Rating Label",
            "dataType": "string",
            "expression": "REPT ( \"*\", DimAccommodation[StarRating] ) & \" (\" & DimAccommodation[StarRating] & \")\"",
            "isDataTypeInferred": true,
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DimAccommodation",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(ServerName, DatabaseName),",
                "    dbo_DimAccommodation = Source{[Schema=\"dbo\",Item=\"DimAccommodation\"]}[Data]",
                "in",
                "    dbo_DimAccommodation"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "DimTransport",
        "columns": [
          {
            "name": "TransportID",
            "dataType": "int64",
            "sourceColumn": "TransportID",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "0",
            "isHidden": true
          },
          {
            "name": "TransportType",
            "dataType": "string",
            "sourceColumn": "TransportType",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Carrier",
            "dataType": "string",
            "sourceColumn": "Carrier",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "TravelClass",
            "dataType": "string",
            "sourceColumn": "TravelClass",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "CostFactor",
            "dataType": "double",
            "sourceColumn": "CostFactor",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "#,0.00"
          },
          {
            "name": "IsInternationalCapable",
            "dataType": "boolean",
            "sourceColumn": "IsInternationalCapable",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Carrier Class",
            "dataType": "string",
            "expression": "DimTransport[Carrier] & \" - \" & DimTransport[TravelClass]",
            "isDataTypeInferred": true,
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DimTransport",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(ServerName, DatabaseName),",
                "    dbo_DimTransport = Source{[Schema=\"dbo\",Item=\"DimTransport\"]}[Data]",
                "in",
                "    dbo_DimTransport"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "DimBookingChannel",
        "columns": [
          {
            "name": "ChannelID",
            "dataType": "int64",
            "sourceColumn": "ChannelID",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "0",
            "isHidden": true
          },
          {
            "name": "ChannelName",
            "dataType": "string",
            "sourceColumn": "ChannelName",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ChannelType",
            "dataType": "string",
            "sourceColumn": "ChannelType",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "CommissionRate",
            "dataType": "double",
            "sourceColumn": "CommissionRate",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "0.0%"
          }
        ],
        "partitions": [
          {
            "name": "DimBookingChannel",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(ServerName, DatabaseName),",
                "    dbo_DimBookingChannel = Source{[Schema=\"dbo\",Item=\"DimBookingChannel\"]}[Data]",
                "in",
                "    dbo_DimBookingChannel"
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Channel Hierarchy",
            "levels": [
              {
                "name": "ChannelType",
                "ordinal": 0,
                "column": "ChannelType"
              },
              {
                "name": "ChannelName",
                "ordinal": 1,
                "column": "ChannelName"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "FactTrip",
        "columns": [
          {
            "name": "TripID",
            "dataType": "int64",
            "sourceColumn": "TripID",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "0",
            "isHidden": true
          },
          {
            "name": "BookingReference",
            "dataType": "string",
            "sourceColumn": "BookingReference",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "TravellerID",
            "dataType": "int64",
            "sourceColumn": "TravellerID",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "0",
            "isHidden": true
          },
          {
            "name": "DestinationID",
            "dataType": "int64",
            "sourceColumn": "DestinationID",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "0",
            "isHidden": true
          },
          {
            "name": "AccommodationID",
            "dataType": "int64",
            "sourceColumn": "AccommodationID",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "0",
            "isHidden": true
          },
          {
            "name": "TransportID",
            "dataType": "int64",
            "sourceColumn": "TransportID",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "0",
            "isHidden": true
          },
          {
            "name": "ChannelID",
            "dataType": "int64",
            "sourceColumn": "ChannelID",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "0",
            "isHidden": true
          },
          {
            "name": "BookingDateKey",
            "dataType": "int64",
            "sourceColumn": "BookingDateKey",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "0",
            "isHidden": true
          },
          {
            "name": "StartDateKey",
            "dataType": "int64",
            "sourceColumn": "StartDateKey",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "0",
            "isHidden": true
          },
          {
            "name": "EndDateKey",
            "dataType": "int64",
            "sourceColumn": "EndDateKey",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "0",
            "isHidden": true
          },
          {
            "name": "DurationDays",
            "dataType": "int64",
            "sourceColumn": "DurationDays",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "#,0"
          },
          {
            "name": "NumTravellers",
            "dataType": "int64",
            "sourceColumn": "NumTravellers",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "#,0"
          },
          {
            "name": "LeadTimeDays",
            "dataType": "int64",
            "sourceColumn": "LeadTimeDays",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "#,0"
          },
          {
            "name": "AccommodationCost",
            "dataType": "decimal",
            "sourceColumn": "AccommodationCost",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "\"₹\"#,0"
          },
          {
            "name": "TransportCost",
            "dataType": "decimal",
            "sourceColumn": "TransportCost",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "\"₹\"#,0"
          },
          {
            "name": "ActivityCost",
            "dataType": "decimal",
            "sourceColumn": "ActivityCost",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "\"₹\"#,0"
          },
          {
            "name": "GrossAmount",
            "dataType": "decimal",
            "sourceColumn": "GrossAmount",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "\"₹\"#,0"
          },
          {
            "name": "DiscountAmount",
            "dataType": "decimal",
            "sourceColumn": "DiscountAmount",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "\"₹\"#,0"
          },
          {
            "name": "Revenue",
            "dataType": "decimal",
            "sourceColumn": "Revenue",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "\"₹\"#,0"
          },
          {
            "name": "ChannelCommission",
            "dataType": "decimal",
            "sourceColumn": "ChannelCommission",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "\"₹\"#,0"
          },
          {
            "name": "NetRevenue",
            "dataType": "decimal",
            "sourceColumn": "NetRevenue",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "\"₹\"#,0"
          },
          {
            "name": "SatisfactionScore",
            "dataType": "double",
            "sourceColumn": "SatisfactionScore",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "#,0.00"
          },
          {
            "name": "BookingStatus",
            "dataType": "string",
            "sourceColumn": "BookingStatus",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "RevenuePerTraveller",
            "dataType": "decimal",
            "sourceColumn": "RevenuePerTraveller",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "\"₹\"#,0"
          },
          {
            "name": "RevenuePerDay",
            "dataType": "decimal",
            "sourceColumn": "RevenuePerDay",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "\"₹\"#,0"
          },
          {
            "name": "BookingWindow",
            "dataType": "string",
            "sourceColumn": "BookingWindow",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "TripLengthBand",
            "dataType": "string",
            "sourceColumn": "TripLengthBand",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Satisfaction Band",
            "dataType": "string",
            "sourceColumn": "Satisfaction Band",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "DiscountPct",
            "dataType": "double",
            "sourceColumn": "DiscountPct",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "0.0%"
          },
          {
            "name": "TravellerDays",
            "dataType": "int64",
            "sourceColumn": "TravellerDays",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "#,0"
          },
          {
            "type": "calculated",
            "name": "Trip Value Category",
            "dataType": "string",
            "expression": "SWITCH ( TRUE(),\n    FactTrip[Revenue] >= 600000, \"1. Premium (6L+)\",\n    FactTrip[Revenue] >= 300000, \"2. High (3-6L)\",\n    FactTrip[Revenue] >= 150000, \"3. Mid (1.5-3L)\",\n    \"4. Entry (<1.5L)\" )",
            "isDataTypeInferred": true,
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Is Cancelled",
            "dataType": "int64",
            "expression": "IF ( FactTrip[BookingStatus] = \"Cancelled\", 1, 0 )",
            "isDataTypeInferred": true,
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "0"
          },
          {
            "type": "calculated",
            "name": "Trip Margin",
            "dataType": "decimal",
            "expression": "FactTrip[NetRevenue] - FactTrip[AccommodationCost] * 0.72 - FactTrip[TransportCost] * 0.88 - FactTrip[ActivityCost] * 0.55",
            "isDataTypeInferred": true,
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "\"₹\"#,0",
            "description": "Estimated gross margin after supplier cost of sale."
          }
        ],
        "partitions": [
          {
            "name": "FactTrip",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(ServerName, DatabaseName),",
                "    dbo_FactTrip = Source{[Schema=\"dbo\",Item=\"FactTrip\"]}[Data],",
                "    #\"Removed Blank Rows\" = Table.SelectRows(dbo_FactTrip, each [TripID] <> null and [Revenue] <> null),",
                "    #\"Filtered Valid Trips\" = Table.SelectRows(#\"Removed Blank Rows\", each [DurationDays] > 0 and [NumTravellers] > 0 and [Revenue] > 0),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Filtered Valid Trips\",{{\"Revenue\", type number}, {\"NetRevenue\", type number}, {\"GrossAmount\", type number}, {\"DiscountAmount\", type number}, {\"SatisfactionScore\", type number}}),",
                "    #\"Added Satisfaction Band\" = Table.AddColumn(#\"Changed Type\", \"Satisfaction Band\", each if [SatisfactionScore] = null then \"Not Rated\" else if [SatisfactionScore] >= 8 then \"Promoter (8-10)\" else if [SatisfactionScore] >= 6 then \"Passive (6-7.9)\" else \"Detractor (<6)\", type text),",
                "    #\"Added Discount Pct\" = Table.AddColumn(#\"Added Satisfaction Band\", \"DiscountPct\", each if [GrossAmount] = 0 then 0 else [DiscountAmount] / [GrossAmount], type number),",
                "    #\"Added Traveller Days\" = Table.AddColumn(#\"Added Discount Pct\", \"TravellerDays\", each [NumTravellers] * [DurationDays], Int64.Type)",
                "in",
                "    #\"Added Traveller Days\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Total Bookings",
            "expression": "COUNTROWS ( FactTrip )",
            "formatString": "#,0",
            "displayFolder": "01 Volume"
          },
          {
            "name": "Total Travellers",
            "expression": "SUM ( FactTrip[NumTravellers] )",
            "formatString": "#,0",
            "displayFolder": "01 Volume"
          },
          {
            "name": "Traveller Days",
            "expression": "SUM ( FactTrip[TravellerDays] )",
            "formatString": "#,0",
            "displayFolder": "01 Volume"
          },
          {
            "name": "Distinct Travellers",
            "expression": "DISTINCTCOUNT ( FactTrip[TravellerID] )",
            "formatString": "#,0",
            "displayFolder": "01 Volume"
          },
          {
            "name": "Distinct Destinations",
            "expression": "DISTINCTCOUNT ( FactTrip[DestinationID] )",
            "formatString": "#,0",
            "displayFolder": "01 Volume"
          },
          {
            "name": "Completed Bookings",
            "expression": "CALCULATE ( [Total Bookings], FactTrip[BookingStatus] = \"Completed\" )",
            "formatString": "#,0",
            "displayFolder": "01 Volume"
          },
          {
            "name": "Cancelled Bookings",
            "expression": "CALCULATE ( [Total Bookings], FactTrip[BookingStatus] = \"Cancelled\" )",
            "formatString": "#,0",
            "displayFolder": "01 Volume"
          },
          {
            "name": "Total Revenue",
            "expression": "SUM ( FactTrip[Revenue] )",
            "formatString": "\"₹\"#,0",
            "displayFolder": "02 Value"
          },
          {
            "name": "Gross Amount",
            "expression": "SUM ( FactTrip[GrossAmount] )",
            "formatString": "\"₹\"#,0",
            "displayFolder": "02 Value"
          },
          {
            "name": "Net Revenue",
            "expression": "SUM ( FactTrip[NetRevenue] )",
            "formatString": "\"₹\"#,0",
            "displayFolder": "02 Value"
          },
          {
            "name": "Total Discount",
            "expression": "SUM ( FactTrip[DiscountAmount] )",
            "formatString": "\"₹\"#,0",
            "displayFolder": "02 Value"
          },
          {
            "name": "Total Commission",
            "expression": "SUM ( FactTrip[ChannelCommission] )",
            "formatString": "\"₹\"#,0",
            "displayFolder": "02 Value"
          },
          {
            "name": "Gross Margin",
            "expression": "SUM ( FactTrip[Trip Margin] )",
            "formatString": "\"₹\"#,0",
            "displayFolder": "02 Value"
          },
          {
            "name": "Revenue (Cr)",
            "expression": "DIVIDE ( [Total Revenue], 10000000 )",
            "formatString": "#,0.00\" Cr\"",
            "displayFolder": "02 Value"
          },
          {
            "name": "Net Revenue (Cr)",
            "expression": "DIVIDE ( [Net Revenue], 10000000 )",
            "formatString": "#,0.00\" Cr\"",
            "displayFolder": "02 Value"
          },
          {
            "name": "Avg Booking Value",
            "expression": "DIVIDE ( [Total Revenue], [Total Bookings] )",
            "formatString": "\"₹\"#,0",
            "displayFolder": "03 Averages"
          },
          {
            "name": "Revenue per Traveller",
            "expression": "DIVIDE ( [Total Revenue], [Total Travellers] )",
            "formatString": "\"₹\"#,0",
            "displayFolder": "03 Averages"
          },
          {
            "name": "Avg Trip Duration",
            "expression": "AVERAGE ( FactTrip[DurationDays] )",
            "formatString": "#,0.00",
            "displayFolder": "03 Averages"
          },
          {
            "name": "Avg Lead Time",
            "expression": "AVERAGE ( FactTrip[LeadTimeDays] )",
            "formatString": "#,0.00",
            "displayFolder": "03 Averages"
          },
          {
            "name": "Avg Satisfaction",
            "expression": "AVERAGE ( FactTrip[SatisfactionScore] )",
            "formatString": "#,0.00",
            "displayFolder": "03 Averages"
          },
          {
            "name": "Avg Party Size",
            "expression": "AVERAGE ( FactTrip[NumTravellers] )",
            "formatString": "#,0.00",
            "displayFolder": "03 Averages"
          },
          {
            "name": "Cancellation Rate %",
            "expression": "DIVIDE ( [Cancelled Bookings], [Total Bookings] )",
            "formatString": "0.0%",
            "displayFolder": "04 Ratios"
          },
          {
            "name": "Net Margin %",
            "expression": "DIVIDE ( [Net Revenue], [Total Revenue] )",
            "formatString": "0.0%",
            "displayFolder": "04 Ratios"
          },
          {
            "name": "Discount Rate %",
            "expression": "DIVIDE ( [Total Discount], [Gross Amount] )",
            "formatString": "0.0%",
            "displayFolder": "04 Ratios"
          },
          {
            "name": "Commission Rate %",
            "expression": "DIVIDE ( [Total Commission], [Total Revenue] )",
            "formatString": "0.0%",
            "displayFolder": "04 Ratios"
          },
          {
            "name": "Gross Margin %",
            "expression": "DIVIDE ( [Gross Margin], [Total Revenue] )",
            "formatString": "0.0%",
            "displayFolder": "04 Ratios"
          },
          {
            "name": "Promoter %",
            "expression": "DIVIDE (\n    CALCULATE ( [Total Bookings], FactTrip[Satisfaction Band] = \"Promoter (8-10)\" ),\n    CALCULATE ( [Total Bookings], NOT ISBLANK ( FactTrip[SatisfactionScore] ) )\n)",
            "formatString": "0.0%",
            "displayFolder": "04 Ratios"
          },
          {
            "name": "Revenue YTD",
            "expression": "TOTALYTD ( [Total Revenue], DimDate[FullDate] )",
            "formatString": "\"₹\"#,0",
            "displayFolder": "05 Time Intelligence"
          },
          {
            "name": "Revenue QTD",
            "expression": "TOTALQTD ( [Total Revenue], DimDate[FullDate] )",
            "formatString": "\"₹\"#,0",
            "displayFolder": "05 Time Intelligence"
          },
          {
            "name": "Revenue PY",
            "expression": "CALCULATE ( [Total Revenue], SAMEPERIODLASTYEAR ( DimDate[FullDate] ) )",
            "formatString": "\"₹\"#,0",
            "displayFolder": "05 Time Intelligence"
          },
          {
            "name": "Revenue YoY",
            "expression": "[Total Revenue] - [Revenue PY]",
            "formatString": "\"₹\"#,0",
            "displayFolder": "05 Time Intelligence"
          },
          {
            "name": "Revenue YoY %",
            "expression": "DIVIDE ( [Revenue YoY], [Revenue PY] )",
            "formatString": "0.0%",
            "displayFolder": "05 Time Intelligence"
          },
          {
            "name": "Revenue PM",
            "expression": "CALCULATE ( [Total Revenue], PREVIOUSMONTH ( DimDate[FullDate] ) )",
            "formatString": "\"₹\"#,0",
            "displayFolder": "05 Time Intelligence"
          },
          {
            "name": "Revenue MoM %",
            "expression": "DIVIDE ( [Total Revenue] - [Revenue PM], [Revenue PM] )",
            "formatString": "0.0%",
            "displayFolder": "05 Time Intelligence"
          },
          {
            "name": "Revenue 3M Moving Avg",
            "expression": "AVERAGEX (\n    DATESINPERIOD ( DimDate[FullDate], MAX ( DimDate[FullDate] ), -3, MONTH ),\n    CALCULATE ( [Total Revenue] )\n)",
            "formatString": "\"₹\"#,0",
            "displayFolder": "05 Time Intelligence",
            "description": "Three-month moving average, used to smooth the seasonal swing on the trend page."
          },
          {
            "name": "Revenue Rolling 12M",
            "expression": "CALCULATE (\n    [Total Revenue],\n    DATESINPERIOD ( DimDate[FullDate], MAX ( DimDate[FullDate] ), -12, MONTH )\n)",
            "formatString": "\"₹\"#,0",
            "displayFolder": "05 Time Intelligence"
          },
          {
            "name": "Running Total Revenue",
            "expression": "CALCULATE (\n    [Total Revenue],\n    FILTER (\n        ALLSELECTED ( DimDate[FullDate] ),\n        DimDate[FullDate] <= MAX ( DimDate[FullDate] )\n    )\n)",
            "formatString": "\"₹\"#,0",
            "displayFolder": "05 Time Intelligence"
          },
          {
            "name": "Bookings by Booking Date",
            "expression": "CALCULATE (\n    [Total Bookings],\n    USERELATIONSHIP ( FactTrip[BookingDateKey], DimDate[DateKey] )\n)",
            "formatString": "#,0",
            "displayFolder": "05 Time Intelligence",
            "description": "Uses the inactive booking-date relationship instead of the travel-date one."
          },
          {
            "name": "Destination Rank",
            "expression": "IF (\n    NOT ISBLANK ( [Total Revenue] ),\n    RANKX ( ALL ( DimDestination[DestinationName] ), [Total Revenue],, DESC, DENSE )\n)",
            "formatString": "0",
            "displayFolder": "06 Ranking"
          },
          {
            "name": "Revenue % of Total",
            "expression": "DIVIDE ( [Total Revenue], CALCULATE ( [Total Revenue], ALLSELECTED ( DimDestination ) ) )",
            "formatString": "0.0%",
            "displayFolder": "06 Ranking"
          },
          {
            "name": "Top 5 Destinations Revenue",
            "expression": "CALCULATE (\n    [Total Revenue],\n    TOPN ( 5, ALL ( DimDestination[DestinationName] ), [Total Revenue], DESC )\n)",
            "formatString": "\"₹\"#,0",
            "displayFolder": "06 Ranking"
          },
          {
            "name": "Pareto Revenue %",
            "expression": "VAR CurrentRev = [Total Revenue]\nVAR AllDest =\n    ADDCOLUMNS ( ALLSELECTED ( DimDestination[DestinationName] ), \"@Rev\", [Total Revenue] )\nVAR CumRev =\n    SUMX ( FILTER ( AllDest, [@Rev] >= CurrentRev ), [@Rev] )\nVAR GrandTotal = SUMX ( AllDest, [@Rev] )\nRETURN\n    DIVIDE ( CumRev, GrandTotal )",
            "formatString": "0.0%",
            "displayFolder": "06 Ranking",
            "description": "Cumulative share of revenue, ordered from the largest destination down."
          },
          {
            "name": "Revenue Target",
            "expression": "VAR PriorYear = [Revenue PY]\nRETURN IF ( NOT ISBLANK ( PriorYear ), PriorYear * 1.15 )",
            "formatString": "\"₹\"#,0",
            "displayFolder": "07 Targets",
            "description": "Business target: 15% growth on the same period last year."
          },
          {
            "name": "Target Variance",
            "expression": "[Total Revenue] - [Revenue Target]",
            "formatString": "\"₹\"#,0",
            "displayFolder": "07 Targets"
          },
          {
            "name": "Target Achievement %",
            "expression": "DIVIDE ( [Total Revenue], [Revenue Target] )",
            "formatString": "0.0%",
            "displayFolder": "07 Targets"
          },
          {
            "name": "Revenue Trend Indicator",
            "expression": "VAR G = [Revenue YoY %]\nRETURN\n    SWITCH ( TRUE(),\n        ISBLANK ( G ), \"\",\n        G >= 0.15, \"▲ Ahead of target\",\n        G >= 0,    \"▲ Growing\",\n        \"▼ Declining\" )",
            "displayFolder": "07 Targets",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Satisfaction Status",
            "expression": "VAR S = [Avg Satisfaction]\nRETURN\n    SWITCH ( TRUE(),\n        ISBLANK ( S ), \"No ratings\",\n        S >= 7, \"Good\",\n        S >= 6, \"Acceptable\",\n        \"Needs attention\" )",
            "displayFolder": "07 Targets",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Revenue at Scenario Discount",
            "expression": "VAR Adj = SELECTEDVALUE ( 'Discount Scenario'[Discount %], 0 )\nRETURN\n    SUMX (\n        FactTrip,\n        FactTrip[GrossAmount] * ( 1 - Adj )\n    )",
            "formatString": "\"₹\"#,0",
            "displayFolder": "08 What-If",
            "description": "Revenue if every booking were sold at the scenario discount instead of its actual one."
          },
          {
            "name": "Scenario Revenue Impact",
            "expression": "[Revenue at Scenario Discount] - [Total Revenue]",
            "formatString": "\"₹\"#,0",
            "displayFolder": "08 What-If"
          },
          {
            "name": "Dynamic Title Destination",
            "expression": "\"Revenue performance - \" & \n    IF ( ISFILTERED ( DimDestination[DestinationName] ),\n        CONCATENATEX ( VALUES ( DimDestination[DestinationName] ), DimDestination[DestinationName], \", \" ),\n        \"all destinations\" )",
            "displayFolder": "09 Titles",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Dynamic Title Period",
            "expression": "VAR MinD = MIN ( DimDate[FullDate] )\nVAR MaxD = MAX ( DimDate[FullDate] )\nRETURN FORMAT ( MinD, \"dd MMM yyyy\" ) & \"  to  \" & FORMAT ( MaxD, \"dd MMM yyyy\" )",
            "displayFolder": "09 Titles",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          }
        ],
        "description": "Trip booking fact table at one row per booking, loaded from the cleaned dbo.FactTrip.",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Discount Scenario",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Discount %",
            "dataType": "decimal",
            "isDataTypeInferred": true,
            "sourceColumn": "[Value]",
            "formatString": "0.0%",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Discount Scenario",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "GENERATESERIES ( 0, 0.30, 0.01 )"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "discount_scenario"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "cafb9bcf-65f3-5cd2-b109-2ae6e5cb363a",
        "fromTable": "FactTrip",
        "fromColumn": "StartDateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      },
      {
        "name": "81189b6f-54fc-5093-9796-d689f9614949",
        "fromTable": "FactTrip",
        "fromColumn": "BookingDateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey",
        "isActive": false
      },
      {
        "name": "1b60aa54-9fed-5349-a7d8-057668b81efd",
        "fromTable": "FactTrip",
        "fromColumn": "EndDateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey",
        "isActive": false
      },
      {
        "name": "50d7eb3c-9070-5c11-b2df-72046181d8f8",
        "fromTable": "FactTrip",
        "fromColumn": "DestinationID",
        "toTable": "DimDestination",
        "toColumn": "DestinationID"
      },
      {
        "name": "ec644f11-4e2d-5afc-a007-7081c677666b",
        "fromTable": "FactTrip",
        "fromColumn": "TravellerID",
        "toTable": "DimTraveller",
        "toColumn": "TravellerID"
      },
      {
        "name": "4328d965-4e42-525a-87c6-34046eed67fe",
        "fromTable": "FactTrip",
        "fromColumn": "AccommodationID",
        "toTable": "DimAccommodation",
        "toColumn": "AccommodationID"
      },
      {
        "name": "bf0b5ea4-bfc6-507e-8020-fc5c1d17ff48",
        "fromTable": "FactTrip",
        "fromColumn": "TransportID",
        "toTable": "DimTransport",
        "toColumn": "TransportID"
      },
      {
        "name": "1ddcc8dd-81b7-54ae-ab16-bd8d47ef2e46",
        "fromTable": "FactTrip",
        "fromColumn": "ChannelID",
        "toTable": "DimBookingChannel",
        "toColumn": "ChannelID"
      },
      {
        "name": "5a5be26f-e90e-5a87-b338-c41d914aa8be",
        "fromTable": "DimAccommodation",
        "fromColumn": "DestinationID",
        "toTable": "DimDestination",
        "toColumn": "DestinationID",
        "isActive": false
      }
    ],
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"ServerName\", \"DatabaseName\", \"DimDate\", \"DimDestination\", \"DimTraveller\", \"DimAccommodation\", \"DimTransport\", \"DimBookingChannel\", \"FactTrip\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ]
  }
}