table FoodExpress_Orders
	lineageTag: e0a97b21-a915-6e65-12ed-ee60e07d1580

	measure 'Total Revenue' = SUM('FoodExpress_Orders'[Revenue])
		formatString: \₹#,0
		lineageTag: bd392fe5-e402-9e08-eca4-791630f69ef8

	measure 'Total Quantity' = SUM('FoodExpress_Orders'[Quantity])
		formatString: #,0
		lineageTag: 524abce4-95ca-62cc-7e7d-a90a3b86434c

	measure 'Total Orders' = COUNTROWS('FoodExpress_Orders')
		formatString: #,0
		lineageTag: a448a1b7-2388-6837-bfc8-3f15c165b1a7

	measure 'Average Order Value' = DIVIDE([Total Revenue], [Total Orders])
		formatString: \₹#,0
		lineageTag: e27effe3-9a15-6039-00fe-932173efd309

	column OrderID
		dataType: string
		lineageTag: 9692bb1b-ae13-3a40-054d-31c1b7d4da86
		summarizeBy: none
		sourceColumn: OrderID

		annotation SummarizationSetBy = Automatic

	column OrderDate
		dataType: string
		lineageTag: 4deb0ea6-d42e-fd2e-0e17-51453e9a87fd
		summarizeBy: none
		sourceColumn: OrderDate

		annotation SummarizationSetBy = Automatic

	column CustomerName
		dataType: string
		lineageTag: 64736b9c-6c0b-cea5-4908-461854115c98
		summarizeBy: none
		sourceColumn: CustomerName

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 7680347a-98d3-71a6-b255-15a20906095b
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Product
		dataType: string
		lineageTag: ccb32840-4c6f-48b2-711f-da373b1dda94
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		formatString: #,0
		lineageTag: fd806f5c-6056-1964-f0d5-9e8dd3a1c27a
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column UnitPrice
		dataType: double
		formatString: \₹#,0.00
		lineageTag: 4d1200de-dc28-c27f-51a0-a7dea6faf9ab
		summarizeBy: sum
		sourceColumn: UnitPrice

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		formatString: 0.00
		lineageTag: 705f8a41-7027-52c5-9bc8-60af44e7c890
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

	column PaymentMode
		dataType: string
		lineageTag: 4f25dad9-43dd-e4a3-a17f-8c74a0b765e4
		summarizeBy: none
		sourceColumn: PaymentMode

		annotation SummarizationSetBy = Automatic

	column ParsedDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: d96c10ef-06c7-223d-82f2-3c979b2a0139
		summarizeBy: none
		sourceColumn: ParsedDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Revenue = 'FoodExpress_Orders'[Quantity] * 'FoodExpress_Orders'[UnitPrice] * (1 - 'FoodExpress_Orders'[Discount])
		dataType: double
		formatString: \₹#,0.00
		lineageTag: bbc9c3a2-fc08-bb46-e1df-671b93f2712d
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition FoodExpress_Orders = m
		mode: import
		source =
				let
				    // Looks for the dataset in the usual places. If you keep it somewhere
				    // else, add that full path to this list - nothing else needs changing.
				    Candidates = {
				        "D:\DVT\Exp-6b\foodexpress_orders_raw.csv",
				        "C:\DVT\Exp-6b\foodexpress_orders_raw.csv",
				        "D:\DVT\6a to 7b\DVT\Exp-6b\foodexpress_orders_raw.csv",
				        "D:\DVT\6a to 7b\DVT\exp6b\foodexpress_orders_raw.csv",
				        "C:\DVT\exp6b\foodexpress_orders_raw.csv",
				        "D:\DVT\exp6b\foodexpress_orders_raw.csv",
				        "C:\DVT\DVT\exp6b\foodexpress_orders_raw.csv",
				        "D:\DVT\DVT\exp6b\foodexpress_orders_raw.csv",
				        "E:\DVT\exp6b\foodexpress_orders_raw.csv",
				        "E:\DVT\DVT\exp6b\foodexpress_orders_raw.csv"
				    },
				    Existing = List.Select(Candidates, each
				        try Binary.Length(File.Contents(_)) > 0 otherwise false),
				    DataFile = List.First(Existing, null),
				    Located = if DataFile = null then error "Could not find foodexpress_orders_raw.csv. Open Transform Data and add its full path to the Candidates list in this query." else DataFile,
				    Source = Csv.Document(File.Contents(Located),[Delimiter=",", Columns=9, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Removed Duplicates" = Table.Distinct(#"Promoted Headers"),
				    #"Filled Customer Name" = Table.TransformColumns(#"Removed Duplicates",
				        {{"CustomerName", each if _ = null or _ = "" then "Not Provided" else _, type text}}),
				    #"Filled Discount" = Table.TransformColumns(#"Filled Customer Name",
				        {{"Discount", each if _ = null or _ = "" then 0 else Number.From(_), type number}}),
				    #"Capitalised Region" = Table.TransformColumns(#"Filled Discount",
				        {{"Region", Text.Proper, type text}}),
				    #"Absolute Quantity" = Table.TransformColumns(#"Capitalised Region",
				        {{"Quantity", each Number.Abs(Number.From(_)), Int64.Type}}),
				    #"Added ParsedDate" = Table.AddColumn(#"Absolute Quantity", "ParsedDate", each
				        if Text.StartsWith([OrderDate], "2025-") then
				            Date.FromText([OrderDate])
				        else if Text.Contains([OrderDate], "/") then
				            Date.FromText([OrderDate], [Format = "dd/MM/yyyy", Culture = "en-GB"])
				        else
				            Date.FromText([OrderDate], [Format = "MM-dd-yyyy", Culture = "en-US"]), type date),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added ParsedDate",{{"OrderID", type text}, {"OrderDate", type text}, {"CustomerName", type text}, {"Region", type text}, {"Product", type text}, {"Quantity", Int64.Type}, {"UnitPrice", type number}, {"Discount", type number}, {"PaymentMode", type text}, {"ParsedDate", type date}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

