table AirLink_Bookings
	lineageTag: d79d12e4-5396-32f4-cc44-da7e88ca99b4

	measure 'Total Bookings' = COUNTROWS('AirLink_Bookings')
		formatString: #,0
		lineageTag: ecbbd4fe-086c-e57d-08a2-4eb8afc7886f

	measure 'Cancelled Bookings' = SUM('AirLink_Bookings'[is_cancelled])
		formatString: #,0
		lineageTag: 5cb0ba74-2622-1327-a8c1-7ba1b925e589

	measure 'Cancellation Rate' = DIVIDE([Cancelled Bookings], [Total Bookings])
		formatString: 0.0%
		lineageTag: f87abea7-ef62-a186-793d-523df982cee0

	measure 'Average Lead Time' = AVERAGE('AirLink_Bookings'[lead_time])
		formatString: #,0.0
		lineageTag: 61879b66-44b1-fed1-eb9d-e13cd9fc63a8

	measure 'Average Fare' = AVERAGE('AirLink_Bookings'[fare])
		formatString: \₹#,0
		lineageTag: 9eae1273-7431-23b1-5ece-8534f2f2bf87

	measure 'Total Fare Revenue' = CALCULATE(SUM('AirLink_Bookings'[fare]), 'AirLink_Bookings'[is_cancelled] = 0)
		formatString: \₹#,0
		lineageTag: 58b96e28-a6b9-96a5-6e34-0611259abb67

	column booking_id
		dataType: string
		lineageTag: e3fb6e08-3109-21cd-7604-842e4fe986b7
		summarizeBy: none
		sourceColumn: booking_id

		annotation SummarizationSetBy = Automatic

	column airline
		dataType: string
		lineageTag: 72919993-cf21-0bab-9f25-82cf707c6efa
		summarizeBy: none
		sourceColumn: airline

		annotation SummarizationSetBy = Automatic

	column travel_year
		dataType: int64
		formatString: 0
		lineageTag: 462de711-dfa6-8db1-2c2e-26bc19b4bec8
		summarizeBy: none
		sourceColumn: travel_year

		annotation SummarizationSetBy = Automatic

	column travel_month
		dataType: string
		lineageTag: abd44caf-309f-0fe8-9f57-ccb777b786d2
		summarizeBy: none
		sourceColumn: travel_month
		sortByColumn: travel_month_no

		annotation SummarizationSetBy = Automatic

	column travel_month_no
		dataType: int64
		lineageTag: fa7d1133-4e96-44fc-6211-94d9cc05608a
		summarizeBy: none
		sourceColumn: travel_month_no

		annotation SummarizationSetBy = Automatic

	column travel_period
		dataType: dateTime
		formatString: Long Date
		lineageTag: 51885fde-87a4-3124-14d7-a9acc817f650
		summarizeBy: none
		sourceColumn: travel_period

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column lead_time
		dataType: int64
		formatString: #,0
		lineageTag: d62aebd3-1570-be52-8dbc-e5e15a325f3b
		summarizeBy: none
		sourceColumn: lead_time

		annotation SummarizationSetBy = Automatic

	column lead_time_band
		dataType: string
		lineageTag: 5550078e-be98-9e85-1137-a19aa36d3527
		summarizeBy: none
		sourceColumn: lead_time_band
		sortByColumn: lead_band_no

		annotation SummarizationSetBy = Automatic

	column lead_band_no
		dataType: int64
		lineageTag: b07f104b-7873-b7c3-13d6-de2d6265d306
		summarizeBy: none
		sourceColumn: lead_band_no

		annotation SummarizationSetBy = Automatic

	column adults
		dataType: int64
		lineageTag: ceeee6b7-457d-57b2-a731-fc129137de1c
		summarizeBy: none
		sourceColumn: adults

		annotation SummarizationSetBy = Automatic

	column children
		dataType: int64
		lineageTag: aa732d28-a351-25bc-b9b3-4bb289838e50
		summarizeBy: none
		sourceColumn: children

		annotation SummarizationSetBy = Automatic

	column infants
		dataType: int64
		lineageTag: 629abd4d-a862-e8b4-438c-a84d05698323
		summarizeBy: none
		sourceColumn: infants

		annotation SummarizationSetBy = Automatic

	column country
		dataType: string
		lineageTag: b012d286-f34a-a01d-9893-48704cd199fc
		summarizeBy: none
		sourceColumn: country

		annotation SummarizationSetBy = Automatic

	column agent
		dataType: int64
		lineageTag: 22605394-354d-9ad6-4fc5-5630bccaf3f8
		summarizeBy: none
		sourceColumn: agent

		annotation SummarizationSetBy = Automatic

	column cabin_class
		dataType: string
		lineageTag: d8dec7cf-a976-cf50-6b72-1f2346c67793
		summarizeBy: none
		sourceColumn: cabin_class

		annotation SummarizationSetBy = Automatic

	column fare
		dataType: double
		formatString: \₹#,0.00
		lineageTag: 2f794a28-07bc-10af-5519-629d61fee897
		summarizeBy: sum
		sourceColumn: fare

		annotation SummarizationSetBy = Automatic

	column is_cancelled
		dataType: int64
		lineageTag: 2f31c910-d3ea-84dd-74a1-5a64c6db5f80
		summarizeBy: none
		sourceColumn: is_cancelled

		annotation SummarizationSetBy = Automatic

	column booking_channel
		dataType: string
		lineageTag: af1f5124-97c2-3fa0-8407-d495173a99d6
		summarizeBy: none
		sourceColumn: booking_channel

		annotation SummarizationSetBy = Automatic

	column reservation_status
		dataType: string
		lineageTag: c0e43f1c-a550-191f-5df2-796fbb203fdb
		summarizeBy: none
		sourceColumn: reservation_status

		annotation SummarizationSetBy = Automatic

	column reservation_status_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4dd5ae8d-9aa4-2a44-5ea5-67c7dcb75154
		summarizeBy: none
		sourceColumn: reservation_status_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column checked_bags
		dataType: int64
		lineageTag: c26ffdf8-14c0-431c-38c1-c3cc3b62bbda
		summarizeBy: none
		sourceColumn: checked_bags

		annotation SummarizationSetBy = Automatic

	column seat_changes
		dataType: int64
		lineageTag: a8ccb27a-8dc7-b4cc-fb5a-ec2af1ebe9b5
		summarizeBy: none
		sourceColumn: seat_changes

		annotation SummarizationSetBy = Automatic

	column total_guests = 'AirLink_Bookings'[adults] + 'AirLink_Bookings'[children] + 'AirLink_Bookings'[infants]
		dataType: int64
		lineageTag: 1b091573-50f0-cb8c-3272-943b4d8daa0e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition AirLink_Bookings = m
		mode: import
		source =
				let
				    // Looks for the dataset in the usual places. If you keep it somewhere
				    // else, add that full path to this list - nothing else needs changing.
				    Candidates = {
				        "D:\DVT\6a to 7b\DVT\exp6c\airlink_bookings_raw.csv",
				        "C:\DVT\exp6c\airlink_bookings_raw.csv",
				        "D:\DVT\exp6c\airlink_bookings_raw.csv",
				        "C:\DVT\DVT\exp6c\airlink_bookings_raw.csv",
				        "D:\DVT\DVT\exp6c\airlink_bookings_raw.csv",
				        "E:\DVT\exp6c\airlink_bookings_raw.csv",
				        "E:\DVT\DVT\exp6c\airlink_bookings_raw.csv"
				    },
				    Existing = List.Select(Candidates, each
				        try Binary.Length(File.Contents(_)) > 0 otherwise false),
				    DataFile = List.First(Existing, null),
				    Located = if DataFile = null then error "Could not find airlink_bookings_raw.csv. Open Transform Data and add its full path to the Candidates list in this query." else DataFile,
				    Source = Csv.Document(File.Contents(Located),[Delimiter=",", Columns=19, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Removed Duplicates" = Table.Distinct(#"Promoted Headers"),
				    #"Removed Corporate Account" = Table.RemoveColumns(#"Removed Duplicates",
				        {"corporate_account"}),
				    #"Cleaned Children" = Table.TransformColumns(#"Removed Corporate Account",
				        {{"children", each if _ = null or _ = "" or _ = "NA" then 0 else Number.From(_), Int64.Type}}),
				    #"Cleaned Fare" = Table.TransformColumns(#"Cleaned Children",
				        {{"fare", each if _ = null or _ = "" or _ = "NA" then 0 else Number.From(_), type number}}),
				    #"Cleaned Country" = Table.TransformColumns(#"Cleaned Fare",
				        {{"country", each if _ = null or _ = "" then "IND" else _, type text}}),
				    #"Cleaned Agent" = Table.TransformColumns(#"Cleaned Country",
				        {{"agent", each if _ = null or _ = "" then 0 else Number.From(_), Int64.Type}}),
				    #"Added Month Number" = Table.AddColumn(#"Cleaned Agent", "travel_month_no", each
				        List.PositionOf({"January","February","March","April","May","June","July","August","September","October","November","December"}, [travel_month]) + 1, Int64.Type),
				    #"Added Travel Period" = Table.AddColumn(#"Added Month Number", "travel_period", each
				        #date(Number.From([travel_year]), [travel_month_no], 1), type date),
				    #"Added Lead Band" = Table.AddColumn(#"Added Travel Period", "lead_time_band", each
				        let d = Number.From([lead_time]) in
				        if d <= 7 then "0-7 days"
				        else if d <= 30 then "8-30 days"
				        else if d <= 90 then "31-90 days"
				        else if d <= 180 then "91-180 days"
				        else "180+ days", type text),
				    #"Added Band Number" = Table.AddColumn(#"Added Lead Band", "lead_band_no", each
				        let d = Number.From([lead_time]) in
				        if d <= 7 then 1 else if d <= 30 then 2 else if d <= 90 then 3
				        else if d <= 180 then 4 else 5, Int64.Type),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Band Number",{{"booking_id", type text}, {"airline", type text}, {"travel_year", Int64.Type}, {"travel_month", type text}, {"travel_month_no", Int64.Type}, {"travel_period", type date}, {"lead_time", Int64.Type}, {"lead_time_band", type text}, {"lead_band_no", Int64.Type}, {"adults", Int64.Type}, {"children", Int64.Type}, {"infants", Int64.Type}, {"country", type text}, {"agent", Int64.Type}, {"cabin_class", type text}, {"fare", type number}, {"is_cancelled", Int64.Type}, {"booking_channel", type text}, {"reservation_status", type text}, {"reservation_status_date", type date}, {"checked_bags", Int64.Type}, {"seat_changes", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

